[package]
name = "flag-bearer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["sync"] }
pin-project-lite = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
