[package]
name = "flag-bearer"
version = "0.1.0"
edition = "2024"

[dependencies]
pin-project-lite = "0.2"
parking_lot = "0.12"
pin-list = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures-testing = { git = "https://github.com/conradludgate/futures-testing" }
futures-util = "0.3"
